<img src="" width="100%" alt="OPIM5641 banner"/>

# Wyndor Glass Simplex Method
### OPIM 5641 — Business Decision Modeling · Module2

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5641-notebooks/blob/main/5_Simplex/Wyndor_Glass_Simplex_Method.ipynb)

*Run me top to bottom — **Runtime → Run all**. Data loads from a stable link, so there's nothing to upload.*

# The Simplex Method: Wyndor Glass Example
**OPIM 5641: Business Decision Modeling - University of Connecticut**
-------------------------------------------------------
**Objectives:**
* Write the simplex tableau for a linear programming problem.
* Use pivoting to find an improved solution.  
* Use the simplex method to solve a linear programming problem that maximizes an objective function.  
* Use the simplex method to find an optimal solution to a real-world application.

# Problem Description
The WYNDOR GLASS CO. produces high-quality glass products, including windows and glass doors. It has three plants. Aluminum frames and hardware are made in Plant 1, wood frames are made in Plant 2, and Plant 3 produces the glass and assembles to products.

Due to declining earnings, top management has decided to revamp the company's product line. Unprofitable products are being discontinued - releasing production capacity to launch two new products having large sales potential.

## Some constraints...
Product 1 requires some of the production capacity in Plants 1 and 3, but none in Plant 2. Product 2 needs only Plants 2 and 3. The marketing division has concluded that the company could sell as much product as could be produced by these plants.  However, because both products would be competing for the same production capacity in Plant 3, it is not clear which *mix* of the two products would be the *most profitable*.

Therefore, an Operations Research (OR) team has been formed to study this question.

## A meeting with management...
After meeting with management, the problem has more concretely been defined as:

* Determine what the production rates should be for the two products in order to maximize their total profit, subject to the restrictions imposed by the limited production capacities avialble in the three plants. Each product will be produced in batches of 20, so the production rate is defined as the number of batches produced per week.

* Because the work on a current batch of a particular product is commonly partially completed by the end of the week,  the production rate can be an integer (1,2,3 batches...) or non-integer (0.5 batches).

* Any combination of production rates that satisfies the restrictions imposed by the limited production capacities is permitted, including none of one product or as much as possible of the other.

## Necessary data
The following data was needed to be gathered:
1. Number of hours of production time available per week in each plant for these new products.
2. Number of hours of production time used in each plant for each batch produced of each new product.
3. Profit per batch produced of each new product. Because no substantial costs will be incurred to initiate the production and marketing of these new products, the total profit from each one is approximately *profit per batch produced* times *the number of batches produced*

In the real-world, you will need to engage a host of stakeholders in order to get this info (engineering, marketing, operations etc.)



Name | Product 1 (production time, hours)| Product 2 (production time, hours)| Production Time (available per week, hours)
---|---|---|---|
Plant 1| 1| 0| 4|
Plant 2| 0| 2| 12|
Plant 3| 3| 2| 18|

### Decision Variables and Objective Function
* $x_1$ = number of batches of product 1 produced per week
* $x_2$ = number of batches of product 2 produced per week
* $Z$ = total profit per week in thousands of dollars from producing these two products

Thus, $x_1$ and $x_2$ are the decision variables for the model. Hence, we obtain the objective function.

$Z = 3x_1 + 5x_2$

The objective is to select the values of $x_1$ and $x_2$ to maximize $Z$ subject to restrictions imposed on their values by the limited production capacities available in the three plants.

### Constraints
The time constraints can be represented as inequalities. The table above indicates that each batch of Product 1 uses one hour of production time in Plant 1 and that only 4 hours per week are available. This can be represented as $x_1 \leq 4 $. Similarly, Plant 2 imposes $2x_2 \leq 12$ and Plant 3 imposes $3x_1 + 2x_2 \leq 18$.

# Original Form of the Model

The problem is to select values of $x_1$ and $x_2$ so as to:

Maximize $Z = 3x_1 + 5x_2$

subject to the constraints:
* $\;x_1\quad\quad\;\;\;\; \leq 4 $
* $\quad\quad\;\; 2x_2\; \leq 12$
* $3x_1 + 2x_2\; \leq 18$

and
* $x_1 , x_2 \geq 0$ (non-negativity)

# Augmented Form of the Model
(slack variables omitted from objective function because coefficients are zero!)

Maximize $Z = 3x_1 + 5x_2$

subject to the constraints:

* $\;x_1\quad\quad\;\;\;\; + x_3 \quad\quad\quad\quad\quad = 4 $
* $\quad\quad\;\; 2x_2\; \quad\quad\quad + x_4 \quad\quad = 12$
* $3x_1 + 2x_2\;\quad\quad\quad\quad\quad +x_5 = 18$

and
* * $x_1 , x_2 , x_3, x_4 , x_5 \geq 0$  (non-negativity)

---

## What is the initial basic solution?

$x_1=0$ and $x_2 = 0$ so...
* $x_3 = 4$
* $x_4 = 12$
* $x_5 = 18$

(0, 0, 4, 12, 18)

# Next, we create the initial simplex tableau

In [ ]:
import numpy as np
from sympy import *
from fractions import Fraction

A = np.array([[1, 0, 1, 0, 0, 4],
              [0, 2, 0, 1, 0, 12],
              [3, 2, 0, 0, 1, 18],
              [-3, -5, 0, 0, 0, 0]])

# convert to sympy array for fractions (later on)

from sympy import Matrix
from sympy import Rational

A = Matrix(A)
pprint(A) # voila - looks great! don't forget the extra p for pretty print

# note: objective function is now in the bottom row of tableau!)

⎡1   0   1  0  0  4 ⎤
⎢                   ⎥
⎢0   2   0  1  0  12⎥
⎢                   ⎥
⎢3   2   0  0  1  18⎥
⎢                   ⎥
⎣-3  -5  0  0  0  0 ⎦

In [ ]:
# want to see it with nice column and row headers?
# use pandas to visualize it

import pandas as pd
tmp = pd.DataFrame(np.array(A))
tmp.columns = ['x1', 'x2','x3', 'x4', 'x5', 'RHS']
tmp.index=['R0', 'R1', 'R2', 'R3']
tmp

    x1  x2 x3 x4 x5 RHS
R0   1   0  1  0  0   4
R1   0   2  0  1  0  12
R2   3   2  0  0  1  18
R3  -3  -5  0  0  0   0

# Next, rewrite the objective function so Z is on the RHS

$-3x_1 - 5x_2 = Z$

and initial basic solution is (0, 0, 4, 12, 18) which gives $Z = 0$

### Now, it's time to start an interation - we rewrite the initial simplex tableau. ($R_3$ is the objective function)

Iteration 1:
* $x_2$ is the entering basic variable
* $x_4$ is the departing basic variable

## Entering Variable

In [ ]:
# make it pretty
import pandas as pd
tmp = pd.DataFrame(np.array(A))
tmp.columns = ['x1', 'x2','x3', 'x4', 'x5', 'RHS']
tmp.index=['R0', 'R1', 'R2', 'R3']
tmp

# apply style to a column
tmp.style\
.apply(lambda x: ['background: lightblue' if x.name == 'x2' else '' for i in x])

## Departing Variable

In [ ]:
# Custom function to color the desired cell
def styling_specific_cell(x,row_idx,col_idx):
    color = 'background-color: yellow; color: red'
    df_styler = pd.DataFrame('', index=x.index, columns=x.columns)
    df_styler.iloc[row_idx, col_idx] = color
    return df_styler

# make it pretty
import pandas as pd
tmp = pd.DataFrame(np.array(A))
tmp.columns = ['x1', 'x2','x3', 'x4', 'x5', 'RHS']
tmp.index=['R0', 'R1', 'R2', 'R3']
tmp

# highlight a single cell pivot element
idx_r = 1
idx_c = 1

# apply style to a column
tmp.style\
.apply(lambda x: ['background: lightblue' if x.name == 'x2' else '' for i in x])\
.apply(lambda x: ['background: lightblue' if x.name == 'R1' else '' for i in x], axis=1)\
.apply(styling_specific_cell, row_idx = idx_r, col_idx = idx_c, axis = None)

## Turn pivot element into a '1'.
Where do we start? Choose the most negative value in $R_3$ (bottom row, objective function) & then conduct a minimum ratio test

\begin{align}
 R_0 = \frac{4}{0} = Inf \to Unbounded!
\end{align}


\begin{align}
 R_1 = \frac{12}{2} = 6 \to Minimum!
\end{align}

\begin{align}
 R_2 = \frac{18}{2} = 9
\end{align}


* $R_1$ has the minimum $b/a$ so $x_2$ can be increased to 6.
* That means the 2 in the pivot element needs to become a 1, and all values above and below must become 0 (**Gauss-Jordan method of elimination**)

## Use GJ elimination to turn all other values above and below pivot element into 0s.

Here are the row operations:

\begin{align}
 R_1^* = \frac{1}{2} R_1
\end{align}

* then  $R_2^*$ = $R_2$ - $2R_1^*$
* and   $R_3^*$ = $R_3$ + $5R_1^*$

### R1

In [ ]:
# R1/2
A[1,:] = Fraction(1,2)*A[1,:] # we are just multiplying by 1/2!
A[1,:] # check your work! all looks great!

Matrix([[0, 1, 0, 1/2, 0, 6]])

### R2

In [ ]:
# R2 - 2R1*
A[2,:] = A[2,:] - 2*A[1,:]
A[2,:]

Matrix([[3, 0, 0, -1, 1, 6]])

### R3

In [ ]:
# R3 + 5R1*
A[3,:] = A[3,:] + 5*A[1,:]
A[3,:]

Matrix([[-3, 0, 0, 5/2, 0, 30]])

## Check your work - feasible solution?

And now let's look at $A$ after Gauss-Jordan elimination.

Is it a feasible solution? Sure is!

In [ ]:
# and now let's look at A after Gauss-Jordan elimation
pprint(A)

⎡1   0  1   0   0  4 ⎤
⎢                    ⎥
⎢0   1  0  1/2  0  6 ⎥
⎢                    ⎥
⎢3   0  0  -1   1  6 ⎥
⎢                    ⎥
⎣-3  0  0  5/2  0  30⎦

In [ ]:
# want to see it with nice column and row headers?
# use pandas to visualize it

import pandas as pd
tmp = pd.DataFrame(np.array(A))
tmp.columns = ['x1', 'x2','x3', 'x4', 'x5', 'RHS']
tmp.index=['R0', 'R1', 'R2', 'R3']
tmp

# highlight a single cell pivot element
idx_r = 2
idx_c = 0

# apply style to a column
tmp.style\
.apply(lambda x: ['background: lightblue' if x.name == 'x1' else '' for i in x])\
.apply(lambda x: ['background: lightblue' if x.name == 'R2' else '' for i in x], axis=1)\
.apply(styling_specific_cell, row_idx = idx_r, col_idx = idx_c, axis = None)

### Any negative numbers in bottom row?
Yup. We have to keep going.

# Pivot #2
The improved solution (above) is not optimal because the bottom row has a negative entry. So, apply another iteration of the simplex method to improve the solution further. Choose $x_1$  as the **entering variable** & $x_5$  is the departing variable. Gauss-Jordan elimination produces the matrices shown below.

\begin{align}
 R_0 = \frac{4}{1} = 4
\end{align}


\begin{align}
 R_1 = \frac{12}{2} = Inf \to Unbounded!
\end{align}

\begin{align}
 R_2 = \frac{6}{3} = 2
\end{align}
Hence, $x_5$ is the **departing variable** (note how it has a single 1 and rest are 0s). $x_2$ can be increased to 2!

## Entering Variable
Since the largest negative number is $-3$ from $x_1$, this is our entering variable.

In [ ]:
# apply style to a column
tmp.style\
.apply(lambda x: ['background: lightblue' if x.name == 'x1' else '' for i in x])

## Let's start with the pivot element

Here are the row operations:

\begin{align}
 R_2^* = \frac{1}{3} R_2
\end{align}

* then  $R_0^*$ = $R_0$ - $R_2^*$
* and   $R_3^*$ = $R_3$ + $3R_2^*$

## R2

In [ ]:
# R2/3
A[2,:] = Fraction(1,3)*A[2,:]
A[2,:] # check your work! good!

Matrix([[1, 0, 0, -1/3, 1/3, 2]])

## R0

In [ ]:
# R0 - R2*
A[0,:] = A[0,:] - A[2,:]
A[0,:] # check your work! good!

Matrix([[0, 0, 1, 1/3, -1/3, 2]])

## R3

In [ ]:
A[3,:] = A[3,:] + 3*A[2,:]
A[3,:] # check your work! good!

Matrix([[0, 0, 0, 3/2, 1, 36]])

## Check your work - feasible solution?
And now let's look at $A$ after Gauss-Jordan elimination.

Is it a feasible solution? Sure is!

In [ ]:
# and now let's look at A after Gauss-Jordan elimation
pprint(A)

⎡0  0  1  1/3   -1/3  2 ⎤
⎢                       ⎥
⎢0  1  0  1/2    0    6 ⎥
⎢                       ⎥
⎢1  0  0  -1/3  1/3   2 ⎥
⎢                       ⎥
⎣0  0  0  3/2    1    36⎦

In [ ]:
# want to see it with nice column and row headers?
# use pandas to visualize it

import pandas as pd
tmp = pd.DataFrame(np.array(A))
tmp.columns = ['x1', 'x2','x3', 'x4', 'x5', 'RHS']
tmp.index=['R0', 'R1', 'R2', 'R3']
tmp

   x1 x2 x3    x4    x5 RHS
R0  0  0  1   1/3  -1/3   2
R1  0  1  0   1/2     0   6
R2  1  0  0  -1/3   1/3   2
R3  0  0  0   3/2     1  36

### Any negative numbers in bottom row?
No! You have found the optimal solution!

You are **DONE!** Time to read off the final solution.


## This implies that the optimal solution is:

### $(x_1 , x_2 , x_3, x_4 , x_5)$ = (2, 6, 2, 0, 0)
### and the maximum value of $Z$ is 36!